basic ui change
Celesta-IITP/CelestaAndroid2k19 pull request #48
Opened 2020-06-15 08:03 UTC by debarghya472

2020-06-19 06:38 UTC, s-ayush2903 commented
@debarghya472 Please consider attaching the visuals of the changes that are proposed in this PR and it would be somewhat better if you follow some semantic PR titles and commit messages that reflect the changes made. And also provide some relevant description as well
* For Example:- You can rephrase this PR's title as:
style: Basic UI changes 
In the same way commit message can also be rephrased

Following these will make it easier for all to make track of changes that are made in the merged patches

2020-06-19 16:19 UTC, debarghya472 commented
<img width="404" alt="Screenshot 2020-06-19 at 9 43 56 PM" src="https://user-images.githubusercontent.com/54908977/85155170-0f40a000-b276-11ea-8545-ed9983de36b8.png">


Requesting suggestion about UI

2020-06-19 21:57 UTC, s-ayush2903 requested changes
As the `HomeFragment.java` class has been deleted, please explain where its corresponding xml layout is being inflated.
* In simpler words, please explain why homeFragment has been deleted and what is the significance of its corresponding layout even after the deletion of corresponding host class

2020-06-19 21:57 UTC, s-ayush2903 commented on app/src/main/res/values/colors.xml
> +    <color name="navigation_background">#99000000</color>
Can you please add some relevant name to the color, something like that lets one know what color it is, similar to the naming practices that have been followed in the above lines of the same file

2020-06-19 22:02 UTC, s-ayush2903 commented
* As I can see in the visual attached, there exists no text below third circular icon(that kinda looks like image/gallery option), please take a note of it. 
* Why there is a bottom navigation bar on the screen(this may be due to emulator), test these changes on some real device and update the screenshot here

2020-06-20 16:48 UTC, amangrobo requested changes
Mention the reason for deleting the HomeFragment

2020-06-20 18:04 UTC, debarghya472 commented
- The changes in the HomeFragment.java doesn't have to do anything with the the layout as they were simple Log tools which is unnecessary. 

- Secondly I've attached a vertical scrollView with the buttons so the rest are not visible

2020-06-26 16:58 UTC, debarghya472 commented
@amangrobo requesting review

2020-06-28 11:43 UTC, amangrobo approved these changes

2020-06-28 11:43 UTC, merged